#!/usr/bin/env python3
"""Extract the CMC42/CMC50 substitution tables from MAME's prot_cmc.cpp
into a Rust source file. Run:

    python3 tools/extract_cmc_tables.py <path-to-prot_cmc.cpp> \
        > pydmg/neogeo/memory/cmc_tables.rs

Doing this mechanically (instead of hand-copying 22 x 256 hex bytes)
guarantees the tables are typo-free.
"""
import re
import sys


def main() -> None:
    src = open(sys.argv[1], encoding="utf-8").read()
    pat = re.compile(r"static const uint8_t (\w+)\[256\]\s*=\s*\{(.*?)\};", re.S)
    out = []
    out.append("// AUTO-GENERATED by tools/extract_cmc_tables.py from MAME's")
    out.append("// src/devices/bus/neogeo/prot_cmc.cpp — do not edit by hand.")
    out.append("//")
    out.append("// NEO-CMC42 / NEO-CMC50 graphics & M1 encryption tables.")
    out.append("")
    for name, body in pat.findall(src):
        # Strip // comments, then collect hex byte literals.
        body = re.sub(r"//[^\n]*", "", body)
        vals = re.findall(r"0x([0-9a-fA-F]{2})", body)
        if len(vals) != 256:
            sys.exit(f"table {name}: expected 256 values, got {len(vals)}")
        out.append(f"pub static {name.upper()}: [u8; 256] = [")
        for i in range(0, 256, 16):
            row = ", ".join(f"0x{v.lower()}" for v in vals[i : i + 16])
            out.append(f"    {row},")
        out.append("];")
        out.append("")
    print("\n".join(out))


if __name__ == "__main__":
    main()
